name: Cross-Browser Tests


jobs:
  matrix-setup:
    name: 'Matrix Setup'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Setting up browser matrix"
    outputs:
      matrix: '["chromium", "firefox", "webkit"]'

  test:
    needs: matrix-setup
    name: 'Tests on ${{ matrix.browser }}'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        browser: ${{ fromJson(needs.matrix-setup.outputs.matrix) }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install browser
      run: npx playwright install --with-deps ${{ matrix.browser }}
    
    - name: Run Playwright tests
      run: npm run test:${{ matrix.browser }}
      env:
        CI: true
        
    - name: Browser test summary
      run: echo "Tests completed for ${{ matrix.browser }} browser" 