name: Cross-Browser Tests

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    name: 'Playwright Tests - ${{ matrix.browser }}'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install all Playwright browsers first
      run: npx playwright install --with-deps
    
    - name: Run Playwright tests
      run: npm run test:${{ matrix.browser }}
      env:
        CI: true 