name: Pre-Merge Tests

on:
  pull_request:
    types: [labeled]

jobs:
  should-run:
    if: ${{ github.event.label.name == 'ready-for-merge' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pull request is ready for merge, running comprehensive test suite"
    outputs:
      run-tests: ${{ github.event.label.name == 'ready-for-merge' }}

  all-tests:
    needs: should-run
    if: ${{ needs.should-run.outputs.run-tests == 'true' }}
    name: 'All Tests'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install all Playwright browsers
      run: npx playwright install --with-deps
    
    - name: Run all Playwright tests
      run: npm test
      env:
        CI: true
    
    - name: Test summary
      if: always()
      run: echo "All tests completed as part of pre-merge verification" 